### ISSUE TITLE
Shared library mapping files

### ISSUE THREAD

**Issue by TravisCardwell** [well-typed/hs-bindgen#381]
As mentioned in [this comment][], we plan on defining mappings from C identifiers (imported from specified headers) to Haskell identifiers (in the specified packages and modules) in text files.

[this comment]: <https://github.com/well-typed/hs-bindgen/issues/294#issuecomment-2621042608>

Specifically, a mapping specifies the following:

* C name - This should be the full C spelling, specifying `struct` or `union` when required.  Examples: `int8_t`, `struct tm`
* One or more C header files - The same C type may be imported from any number of header files.  A C type with the specified C name is matched if it is made available by a specified header file, even if it is defined in a different header file that is (transitively) included by the specified header file.  The header file should be specified as used in the C source code (relative to an include directory).
* Haskell package
* Haskell module
* Haskell identifier

@edsko suggested using [YAML][].  That sounds good to me.  There are many people who *hate* YAML, and perhaps we could *also* support [JSON][] if this becomes an issue.  The [`yaml`][] package uses the [`aeson`][] data model, so it is trivial to support both.  Why do people hate YAML?  [The yaml document from hell][] is a blog post that explains some of the complications of the format, a common reason for the YAML hate.

[YAML]: <https://yaml.org/spec/1.2.2/>
[JSON]: <https://www.json.org/>
[`yaml`]: <https://hackage.haskell.org/package/yaml>
[`aeson`]: <https://hackage.haskell.org/package/aeson>
[The yaml document from hell]: <https://ruudvanasseldonk.com/2023/01/11/the-yaml-document-from-hell>

**Comment by TravisCardwell** [comment]
Do we want to specify a filename convention for the mapping files?  I am leaning toward not doing so, just requiring a `.yaml` extension.  Examples:

* `base.yaml` - mappings for types defined in `base`
* `hs-bindgen-runtime-libc.yaml` - mappings for types defined in module `HsBindgen.Runtime.LibC` of package `hs-bindgen-runtime`

Thoughts/preferences?

**Comment by TravisCardwell** [comment]
@edsko and I have a call later today, and I would like to decide on the schema for mapping files.  Checking for strong preferences is probably a good idea before I implement it.

BTW, I am happy to create a [JSON Schema][] if desired.

[JSON Schema]: <https://json-schema.org/specification>

I generally follow the "best practice" of not putting data in keys.  A document is therefore an array of objects with constant keys.  This means that the same C name could be listed more than once in a file, but we can check for this and raise an error.  (Note that the same key can be listed more than once in an object as well, and `aeson` does not provide a way to deal with this, so we would not be able to raise an error with such a design.)

One option is to make the schema as simple as possible, at the expense of repetition.  Note that I recommend *not* using YAML references/inheritance.

```yaml
---

- cname: int8_t
  headers:
    - stdint.h
    - inttypes.h
  package: base
  module: Data.Int
  identifier: Int8

- cname: int16_t
  headers:
    - stdint.h
    - inttypes.h
  package: base
  module: Data.Int
  identifier: Int16

# ...

- cname: uint8_t
  headers:
    - stdint.h
    - inttypes.h
  package: base
  module: Data.Word
  identifier: Word8

- cname: uint16_t
  headers:
    - stdint.h
    - inttypes.h
  package: base
  module: Data.Word
  identifier: Word16

# ...
```

Another option, which reduces the repetition, is to implement defaults in the parser.  The data model remains compatible with any JSON-compatible format.  A downside is that utility programs cannot usefully process such files since external logic constructs the records through sequential processing.

```yaml
---

- defaults:
    headers:
      - stdint.h
      - inttypes.h
    package: base
    module: Data.Int

- cname: int8_t
  identifier: Int8

- cname: int16_t
  identifier: Int16

# ...

- defaults:
    module: Data.Word

- cname: uint8_t
  identifier: Word8

- cname: uint16_t
  identifier: Word16

# ...
```

I would also like to confirm that we will not need to implement conditionals.  For example, a library may use CPP to conditionally provide a certain type.  In such a case, separate mapping files need to be created (for each combination of configuration).

**Comment by TravisCardwell** [comment]
Notes from the call with @edsko :

* Idea: We could use a mapping file to tell `hs-bindgen` what to include when generating bindings for a shared library.  For example, `LibC` only contains some types from the standard library, as others are defined in `base`.

* To make the schema extensible, we should organize into sections (object).  The array of mappings in the above example should go into a section named `types`.  See the new example below.  In the future, we will likely need a `macros` section that lists macros *with types*.  If we implement the above idea, we would also need a `functions` section to list function mappings.

* We will go with the simple data model.  If there are concerns about repetition, would could add support for [Dhall][] in the future.

* Regarding filenames, `${PACKAGE}.${EXTENSION}` should work.  Each package should provide at most one shared library.  Examples: `base.yaml` and `hs-bindgen-runtime.yaml`

[Dhall]: <https://dhall-lang.org/>

Example mapping file:

```yaml
---

types:
  - cname: int8_t
    headers:
      - stdint.h
      - inttypes.h
    package: base
    module: Data.Int
    identifier: Int8

  - cname: int16_t
    headers:
      - stdint.h
      - inttypes.h
    package: base
    module: Data.Int
    identifier: Int16

  # ...
```
