### ISSUE TITLE
Generalize "external bindings" to "binding specifications"

### ISSUE THREAD

**Issue by edsko** [well-typed/hs-bindgen#608]
External bindings currently map C identifiers to Haskell identifiers:

```yaml
types:
- headers: simple_structs.h
  cname: S2_t
  module: Example
  identifier: S2_t
```

This will need to be extended with additional information:

- We need to track which instances are available (#558)
- We might need to to know which types are newtypes around other types for the userland CAPI work (and indeed, which types are _aliases_, #308)
- Macro types (#423)
- ...

At the moment we use these only when referring to _existing_ bindings. The main idea of this ticket is to generalize this so that it's also usable when generating _new_ bindings; hence changing the name to binding _specification_. 

We consider the consequences of this generalization for each piece of information separately.

We should have the following consistency property: if we are _generating_ bindings according to a certain specification, then that same specification should be a valid specification _of_ those generated bindings (that is, it should be usable in reference mode). It might be an underspecification; since `hs-bindgen` also _produces_ a binding spec for bindings that it generates, this produced spec should be a strict "superset" of the input specification.

### Haskell module/identifier

```yaml
types:
- headers: simple_structs.h
  cname: S2_t
  haskell:
    module: Example
    identifier: S2_t
```

**Reference mode**: the C identifier is defined in module `Example` and has name `S2_t`.  
**Generation mode**: please call the type you're going to generate `S2_t` and place it in module `Example`.

This would then subsume #564 (support for name overrides) and (part of) #75 (generating multiple Haskell modules from a single C header).

_Absent value_: We should be careful about what it means for sections to be _absent_. For the `haskell` section: In reference mode it currently means "there is no Haskell type for this _yet_, please generate one". In generation mode we probably don't want it to mean "do not generate a Haskell type", but rather "just do the default". It would perhaps be good to have an _explicit_ syntax for "no value", maybe something like

```yaml
types:
- headers: simple_structs.h
  cname: S2_t
  haskell: nil
```

### Instances

```yaml
types:
- headers: simple_structs.h
  cname: S2_t
  instances: [Eq, Ord, Show, Storable]
```

**Reference mode**: The Haskell type corresponding to the C identifier has the specified instances.
**Generation mode**: Please generate instances for the specified classes. 

This therefore subsumes #307 (configure which instances to generate).

_Absent values_: reference mode (this is not yet implemented either): I think the only reasonable assumption here is there are _no_ instances available? In generation mode, the absent value should mean "the _default_ set of classes you can generate", with an explicit `nil` meaning: nothing. 

This is compatible with the consistency principle only if the "default set of classes" is in-principle-unknowable. In other words, if no list of instances is provided, then you _might_ get an `Eq` instance, but you should not rely on it. If you _do_ want rely on it, you should list it (and then it's an error if that instance cannot be generated).
Perhaps it would be useful to have something like

```yaml
types:
- headers: simple_structs.h
  cname: S2_t
  instances: 
    Eq: yes
   Ord: no
```

so that we can be explicit about which instances we _definitely_ want, which instances we definitely _don't_ want, and use defaults for everything else?

### Newtype/type alias information

```yaml
types:
- headers: simple_structs.h
  cname: S2_t
  newtype: ..
```

and

```yaml
types:
- headers: simple_structs.h
  cname: S2_t
  type-alias: ..
```

(not sure what information we need exactly, or which keys to best use).

**Reference mode**: Give information about which types are type aliases for or newtypes around other types (for example, for use in userland CAPI).
**Generation mode**: Choose when to use newtypes / type aliases 

_Absent value_: in reference mode, this would mean that the datatype is not an alias or a newtype, and should be considered a completely independent datatype. In generation mode: means "use default". Explicit `nil`: not supported?

### Macro types

```yaml
macros:
- headers: ..
  cname: ..
  type: ..
```

(This is a sketch, we don't support this yet in reference mode either.) 

**Reference mode**: This macro exists, and has the specified type.
**Generation mode**: Verify that the macro has the specified type (could conceivably use subsumption here, so request that we use a less polymorphic type for the macro).

_Absent value_: in reference mode: type unknown, in generation mode: no requirements.

**Comment by TravisCardwell** [comment]
**Instances**

> *Absent values*: reference mode (this is not yet implemented either): I think the only reasonable assumption here is there are no instances available?

This is already implemented in the branch that I am currently working on.  In this implementation, not specifying values indeed means that there are no instances available.

> Perhaps it would be useful to have something like

```yaml
types:
- headers: simple_structs.h
  cname: S2_t
  instances:
  - Eq
  - Ord: nil
  - Bounded: newtype
```

> so that we can be explicit about which instances we *don't* want and which instances we *do* want, and for instances we do want, what *kind* of instance ("default" if left otherwise unspecified).  This makes it possible to leave out classes for which we just want to apply the defaults ("generate `Storable` if you can").

Perhaps `instances` is parsed into a type like the following?

```haskell
Map HsTypeClass (Maybe HsDerivingStrategy)
```

My interpretation of the intended behavior:

* When just a type class is specified, the map value is `Just DeriveDefault`, which would allow `hs-bindgen` to choose how to derive an instance.  It is an error if the instance cannot be derived.
* When an object with a `nil` (string?) value is specified, the map value is `Nothing`, which would allow `hs-bindgen` to choose how to derive an instance.  It is *not* an error if the instance cannot be derived.
* When an object with a strategy (non-`nil` string) value is specified, the map value is `Just` that strategy.  It is an error if the instance cannot be derived using that strategy.

An example of when a user might want to configure the strategy is deriving a `Bounded` instance for a Haskell type representing a C `enum`.  When a user requests the instance, perhaps the default would be to use `DerivingVia` to derive the instance using `AsCEnum` or `AsSequentialCEnum` (depending on if the values are sequential or not).  Specifying `newtype` would instead derive the instance so that the bounds are that of the underlying integral type.

Should the specification support a `via` strategy with an argument, such as `via AsSequentialCEnum`?

I would like to humbly propose that we design the specification schema so that it is easy to work with using external tooling.  Example:

```yaml
types:
- headers: simple_structs.h
  cname: S2_t
  instances:
  - Eq
  - class: Ord
    required: false
  - class: Bounded
    strategy: newtype
```

Notes:

* An instance specification can be parsed from a string (with default options) or from an object.  This is no problem *if* we assume that external tooling is only used to write specifications.  Specifications generated from external tooling (including Dhall) would always output the object form, but `hs-bindgen` can of course output the string form when using default options.
* This separates `required` (default `true`) and `strategy` options.  Perhaps a user may want to specify a strategy for an optional instance?
* All object keys are constant.

General notes:

* I recommend avoiding using the string `nil`.  We could use the `null` value, but using `null` to express meaning (not just absence) often causes problems.  Alternatives include using `false` or representing a sum type using strings (such as `Nothing`).
* I recommend avoiding the `-` character in object keys.  We should use the `_` character instead.  Example: `type_alias`, but perhaps just `alias` would be sufficient.

**Macro types**

`newtype` types that are generated from macros are already included in the `types` section.

**Comment by TravisCardwell** [comment]
Current plan:

* [x] Explore design space, determine target design
* [x] Implement new `HsBindgen.BindingSpecs` module
    * Types, JSON/YAML, API
* [x] Migrate `base` and `hs-bindgen-runtime` binding specifications
* [ ] Integrate `HsBindgen.BindingSpecs`, removing `HsBindgen.ExtBindings`
    * Maintain current functionality, do not add new functionality yet
* [ ] Add input binding specifications, implement name customization
* [ ] Implement instance constraints
* [ ] Implement instance customization
* [ ] Update manual

The following are *not* planned yet.  We need to decide on the target design before proceeding:

* Module customization
* `newtype` (vs. type alias) customization
* Macro type customization

**Comment by TravisCardwell** [comment]
Working on integration, we now need to make decisions about the exact semantics of binding specifications.  The goal is to use the same specification format to configure how bindings are generated as well as to specify existing ("external") bindings.  When using external bindings, we need to decide how to handle the various options that are really for configuration.

**(1)** The usual case (currently) has the same options as the old external bindings design.  The Haskell module and identifier are moved into a `haskell` object.

```yaml
types:
- headers: example.h
  cname: foo_t
  haskell:
    module: Example
    identifier: Foo
  instances:
    - Eq
    - Ord
    - Show
```

Perhaps all binding specifications that we generate should be in this form.

**(2)** The `haskell` entry is optional.  This allows users to configure instances without having to configure the Haskell module or identifier.

```yaml
types:
- headers: example.h
  cname: foo_t
  instances:
    - Eq
    - Ord
    - Show
```

In this case, there is not enough information to use an external binding.  Perhaps we should treat this as an error.  Alternatively, we could treat this as if there no configuration for the C type.

**(3)** The `haskell` entry can be `omit`.  This allows users to instruct `hs-bindgen` to not generate a Haskell type at all.

```yaml
types:
- headers: example.h
  cname: foo_t
  haskell: omit
```

Perhaps we should throw an error if the type is used.

**(4)** The `strategy` can be specified for an instance.  This allows users to configure how to derive/generate a specific instance.

```yaml
types:
- headers: example.h
  cname: foo_t
  haskell:
    module: Example
    identifier: Foo
  instances:
    - Eq
    - Ord
    - class: Show
      strategy: newtype
```

The strategy is not relevant to external bindings, so it can simply be ignored.  The type is assumed to have the instance.

**(5)** By setting `strategy` to `omit`, users can instruct `hs-bindgen` to
not derive/generate an instance.

```
types:
- headers: example.h
  cname: foo_t
  haskell:
    module: Example
    identifier: Foo
  instances:
    - Eq
    - Ord
    - class: Show
      strategy: omit
```

The set of classes for an external binding should be all those listed except for those with `strategy` set to `omit`.

**Comment by TravisCardwell** [comment]
I finished the integration.  One note about the current design is that the term "external binding" is still used.  We need to distinguish between the binding specification used to configure binding generation from the binding specifications used to specify external bindings.  Both use the same "binding specification" types / YAML file format.  Internally, type `ExtType` represents resolved external bindings, since the error cases mentioned in the previous comment are handled when the bindings are resolved.

Status:

* [x] Explore design space, determine target design
* [x] Implement new `HsBindgen.BindingSpecs` module
    * Types, JSON/YAML, API
* [x] Migrate `base` and `hs-bindgen-runtime` binding specifications
* [x] Integrate `HsBindgen.BindingSpecs`, removing `HsBindgen.ExtBindings`
    * Maintain current functionality, do not add new functionality yet
* [ ] Add input binding specifications, implement name customization
* [ ] Implement instance constraints
* [ ] Implement instance customization
* [ ] Update manual

**Comment by TravisCardwell** [comment]
I added "input" binding specifications (used to configure binding generation) and am currently working on name customization.

When we parse C headers, folding the Clang AST, we construct our C AST such that relations between AST nodes are established using `C.Type`.  This essentially references by C name, though we use `DeclPath` to support references to types that have no C name spelling.  When we translate the C declarations to Haskell declarations, we translate such references by name as well.  We just need to generate consistent code; if we do not, failure happens when GHC attempts to compile the inconsistent code, not during `hs-bindgen` execution.

Binding specifications for a type (`TypeSpec`) are now associated with C AST nodes.  When we translate a declaration, we can check the `TypeSpec` for a custom name and use it.  All references to that type need to also be customized.  My idea for this is add state that tracks the translations of names.  While we currently use the name mangler to construct names of referenced types, we would instead query the translated names in the state.  This should not be difficult to implement since we already order the declarations, and we already use the `State` monad to track instances.

Field names are created by the name mangler using the `C.Type` information.  If a binding specification is used to customize the name of a type, however, we should probably use that customized name when generating field names as well.  Perhaps the name mangler should be changed to use the Haskell type/constructor name, instead of reconstructing it from the `C.Type` information.  Also, we may want to add support for customizing field names.

Support for omitted types is implemented.  Note that dependency on an omitted type results in an error.  Example:

```c
typedef int foo;

struct bar { foo a; };
```

```yaml
types:
- headers: example.h
  cname: foo
  haskell: omit
```

Support for required types needs to be added, and I think that the added state provides a good way to do this.  After the `C` declarations have been translated to `Hs` declarations, the final state can be used to check that all required types are accounted for.

I am not working on customizing which code goes into which modules yet, but I have been thinking about it.  I think it might be another use case for `DynGraph`, as we need to resolve imports as well as check that there are no circular module dependencies.  This should likely be done before the `Hs` declarations are generated, at the beginning of the `Hs` phase.

Thoughts?

**Comment by TravisCardwell** [comment]
I think the vast majority of "input" binding specs will *not* need to customize the module for any types.  Perhaps we should make it optional, so that users only need to specify it when customization is needed.

We talked a bit about it before, but I (still) think it is worth considering *not* being clever with `omit` syntax and instead use a separate property.  We could use a boolean `omit` property, where the default value of `False` means that the type is required.  If we want to avoid booleans, we could use a property called `presence` with possible values `require` (the default value) and `omit`.  In either case, we would then be able to use the same shortcut syntax for `haskell` specifications as we do for instance specifications.

Example: customize the name:

```yaml
types:
  - headers: example.h
    cname: foo_t
    haskell: Foo
```

Example: customize the name and module:

```yaml
types:
  - headers: example.h
    cname: foo_t
    haskell:
      module: Bar
      identifier: Foo
```

Example: omit the type with `omit`:

```yaml
types:
  - headers: example.h
    cname: foo_t
    omit: true
```

Example: alternatively, omit the type with `presence`:

```yaml
types:
  - headers: example.h
    cname: foo_t
    presence: omit
```

IMHO, the following would be much better than the overloaded `strategy: omit`.

```yaml
types:
  - headers: example.h
    cname: foo_t
    instances:
      - class: Show
        omit: true
```

Might users want to customize the module without having to specify the name?  The separate `omit`/`presence` property also makes it possible to remove the `haskell` object.

Example: customize the name:

```yaml
types:
  - headers: example.h
    cname: foo_t
    hsname: Foo
```

Example: customize the module:

```yaml
types:
  - headers: example.h
    cname: foo_t
    module: Bar
```

IMHO, such changes result in better aesthetics, but I think that they are better from a technical perspective as well because it is future-proof.  The clever usage may someday cause us to implement distasteful workarounds when additions are made to the schema.

Thoughts?

**Comment by TravisCardwell** [comment]
> My idea for this is add state that tracks the translations of names.

While instances can be resolved with a single traversal thanks to the order of declarations, names cannot.  Forward references are still possible, behind pointers.

Perhaps this is most easily resolved by doing two traversals.  The first traversal can simply construct a mapping of type name translations, and the second traversal can resolve instances and generate the Haskell declarations.

We could avoid two traversals if we translated names in the `C` phase, as the Clang AST is folded.  This would put (more) Haskell stuff in the `C` phase, though, so it is unpalatable.

**Comment by TravisCardwell** [comment]
> Field names are created by the name mangler using the C.Type information. If a binding specification is used to customize the name of a type, however, we should probably use that customized name when generating field names as well.

This applies to constructors as well.  Example:

```c
typedef struct foo {
  int a;
} foo_t;

struct bar {
  foo_t b;
};
```

```yaml
types:
  - headers: example.h
    cname: foo_t
    haskell:
      module: Example
      identifier: FooT
```

```
$ cabal run hs-bindgen-cli -- preprocess \
    --binding-specs example.yaml \
    -i example.h
```

```haskell
...
newtype FooT = Foo_t
  { un_Foo_t :: Foo
  }
...
```

The type constructor is customized in the binding specifications.  The name mangler creates the names for the constructor and field using the `DeclPath`, however, resulting in the inconsistent naming.  If we instead pass the type constructor name in the context, we could create consistent names `FooT` and `un_FooT`.

**Comment by TravisCardwell** [comment]
The current implementation does not yet provide a way to customize macro types.  I wonder if it would be worthwhile to refactor the macro types so that there are separate constructors for type-like macros and variable-like macros.  Currently, we perform a number of checks to distinguish these each time we work with a macro.  Type-like macros will need to be associated with a `Maybe TypeSpec`, while variable-like macros will need to be associated with a `Maybe VarSpec` (not yet implemented).

**Comment by TravisCardwell** [comment]
Status:

* [x] Explore design space, determine target design
* [x] Implement new `HsBindgen.BindingSpecs` module
* [x] Migrate `base` and `hs-bindgen-runtime` binding specifications
* [x] Integrate `HsBindgen.BindingSpecs`, removing `HsBindgen.ExtBindings`
* [x] Add input binding specifications
* [x] Implement name customization
    * Macro name customization not supported yet
* [ ] Implement instance constraints (#648)
* [ ] Implement instance customization
* [ ] Write tests
* [ ] Update manual

**Comment by TravisCardwell** [comment]
We currently define the following strategies.

```haskell
data DeriveStrategy =
    DeriveNewtype
  | DeriveStock
  | DeriveViaAsCEnum
  | DeriveViaAsSequentialCEnum
```

The binding specifications use the following type.

```haskell
Maybe (Omittable (DeriveStrategy))
```

As noted in an above comment, I think that separating `Omittable` would be a good idea.  If we do that, the type would be as follows.

```haskell
Maybe DeriveStragey
```

A `Nothing` value is used to indicate that `hs-bindgen` should choose how to derive/generate an instance.  We do not have a way to explicitly request that `hs-bindgen` generate an instance.  This is not a problem as long as `hs-bindgen` generation is always the default for any type class that includes it as a strategy.  This is what we do, but we also provide `TranslationOpts` that allow users to customize the defaults.  Perhaps it would be a good idea to provide a way to explicitly request the `hs-bindgen` strategy.

```haskell
data Strategy =
    StrategyHsBindgen
  | StrategyNewtype
  | StrategyStock
  | StrategyViaAsCEnum
  | StrategyViaAsSequentialCEnum
```

We would still use the `Maybe`, and the `Nothing` value would have the same meaning.

Thoughts?

**Comment by TravisCardwell** [comment]
@edsko and I were able to discuss the design yesterday.  He is not a fan of `presence: omit` or `omit: true`.  The reason is the general principle described above:

> If a value for a certain item is absent in the input spec, the output spec is free to have any value (including none) for that item

I interpreted this as apply to each item/object, but it should be interpreted as applying to every part of the configuration.  For this reason, we should not rely on Aeson default values.  A default of `presence: require` violates this general principle because not writing this should mean that `hs-bindgen` is free to choose the presence.  A default of `omit: false` violates this general principle for the same reason.

The current design is problematic, so @edsko suggested moving the `Omittable` up, to wrap the omitted value.  This indeed resolves the semantic design issue.

Example of omitting a type:

```yaml
types:
  - omit:
      headers: example.h
      cname: foo_t
```

Example of omitting an instance:

```yaml
types:
  - headers: example.h
    cname: foo_t
    instances:
      - omit: Show
```

This makes it clear what is being omitted.  I will implement it and see how well it works.
